/**
 * Generate the 5chan directory contest manifest from the canonical directory list at
 * https://github.com/bitsocialnet/lists/tree/master/5chan-directories
 * (5chan-directories-defaults.json — the file that defines which directory codes exist
 * and their display titles).
 *
 * Emits TWO byte-equivalent representations of the SAME manifest object:
 *   - shared/directory-manifest.json — shipped to the seeder (bitsocial-seeder consumes
 *     JSON/JSONC manifest files or URLs via its votes manifest sources)
 *   - shared/directory-manifest.ts   — imported by the site bundle and the repo scripts
 *     (a .ts module sidesteps JSON-import attribute differences across vite/tsx/node)
 *
 * Both are GENERATED — edit THIS script (the defaults below or the naming scheme) and
 * re-run `npm run manifest`, never the emitted files. Any change to `defaults` or an
 * entry re-derives that contest's criteria bytes and therefore FORKS its topic
 * (topic = "bitsocial-votes/" + CID(dag-cbor(criteria))): redeploy site + seeder together.
 *
 * Usage: tsx scripts/generate-directory-manifest.ts
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { deriveDirectoryCriteria } from "@bitsocial/pubsub-voting";

const DEFAULTS_URL =
    "https://raw.githubusercontent.com/bitsocialnet/lists/master/5chan-directories/5chan-directories-defaults.json";

/**
 * Contest rules shared by every directory slot — the same 5chan Pass gate the
 * single-contest test ran (see the deployment history in README / git log): one vote per
 * wallet holding ≥1 FiveChanPass ERC-721 on Base Sepolia, ~1 h buckets, ~30 d expiry.
 */
const defaults = {
    voteSchema: { min: 1, max: 1 },
    maxVotesPerAddress: 1,
    blocksPerBucket: 1800,
    voteExpiryBuckets: 720,
    rule: {
        type: "erc721-min-balance",
        chain: "baseSepolia",
        contract: "0xa0095E8B45EBd2Fc590FeBC249bBc191D74920a9",
        min: 1
    },
    weight: { type: "constant", value: 1 },
    requires: {
        rules: ["erc721-min-balance", "constant"],
        chains: { baseSepolia: { chainId: 84532 } }
    }
};

/** Bump the suffix to fork EVERY directory contest at once (fresh test run). */
const CONTEST_ID_SUFFIX = "vote-test-1";
export const contestIdFor = (code: string) => `5chan-dir-${code}-${CONTEST_ID_SUFFIX}`;

async function main() {
    const res = await fetch(DEFAULTS_URL);
    if (!res.ok) throw new Error(`fetching ${DEFAULTS_URL} failed: ${res.status}`);
    const list = (await res.json()) as {
        directories: Record<string, { directoryCode: string; title: string }>;
    };

    const codes = Object.keys(list.directories).sort();
    const contests = codes.map((code) => ({
        // e.g. "/g/ - Technology directory (test)" — part of the criteria bytes.
        name: `${list.directories[code].title} directory (test)`,
        contestId: contestIdFor(code)
    }));

    const manifest = {
        name: "5chan directories vote (test)",
        description:
            "One contest per 5chan directory slot: the boards competing to host each directory code. " +
            "Generated by scripts/generate-directory-manifest.ts from " +
            DEFAULTS_URL,
        defaults,
        contests
    };

    // Validate NOW, not at deploy time: every derived document must pass CriteriaSchema
    // and carry a unique contestId, through the same library helper site + seeder use.
    const derived = deriveDirectoryCriteria(manifest);

    const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
    const json = JSON.stringify(manifest, null, 4);
    const banner =
        "GENERATED by scripts/generate-directory-manifest.ts — do not edit by hand.\n" +
        "Any change to defaults or an entry forks that contest's topic; redeploy site + seeder together.";

    writeFileSync(join(repoRoot, "shared", "directory-manifest.json"), `${json}\n`);
    writeFileSync(
        join(repoRoot, "shared", "directory-manifest.ts"),
        `/**\n * ${banner.split("\n").join("\n * ")}\n */\nexport const directoryManifest = ${json} as const;\n`
    );
    console.log(`wrote shared/directory-manifest.{json,ts}: ${derived.length} contests (${codes.join(", ")})`);
}

main().catch((err) => {
    console.error(err);
    process.exit(1);
});
